### ISSUE TITLE
Broken Link in README.md

### ISSUE THREAD

**Issue by ShakedDovrat** [pdollar/toolbox#10]
Hi! This toolbox looks cool.
I'd like to know more about it.
Unfortunately, the link in the README.md file is broken:
http://vision.ucsd.edu/~pdollar/toolbox/doc/
Where can I get the info about this toolbox?

**Comment by pdollar** [comment]
The UCSD vision site appears to be down, please check again in a day or
two. Alternatively, all the documentation is available on GitHub.
