### ISSUE TITLE
vbb and dbInfo problem

### ISSUE THREAD

**Issue by tomtomkite** [pdollar/toolbox#12]
When I want to redo the Pedestrian Detection experiment with the ACF detector,I got failed in the "vbb" and "dbInfo" functions in the demo script. I can not find the functions. Please help me to solve the issues. Thanks.

**Comment by pdollar** [comment]
Please see https://github.com/pdollar/toolbox/blob/master/detector/acfReadme.m for setup instructions. Thanks.
