### ISSUE TITLE
Extract haar-like feature with the toolbox

### ISSUE THREAD

**Issue by yu542469940** [pdollar/toolbox#18]
hi, piotr
I want to detect pedestrain with the traditional haar features. Could you tell me is there something about haar-like feature extraction in this toolbox. thanks!

Best regards,
xiao yu

**Comment by pdollar** [comment]
Please see the associated papers for details about the detector:

% The detector was introduced and described through the following papers:
%  [1] P. Dollár, Z. Tu, P. Perona and S. Belongie
%   "Integral Channel Features", BMVC 2009.
%  [2] P. Dollár, S. Belongie and P. Perona
%   "The Fastest Pedestrian Detector in the West," BMVC 2010.
%  [3] P. Dollár, R. Appel and W. Kienzle
%   "Crosstalk Cascades for Frame-Rate Pedestrian Detection," ECCV 2012.
%  [4] P. Dollár, R. Appel, S. Belongie and P. Perona
%   "Fast Feature Pyramids for Object Detection," PAMI 2014.
%  [5] W. Nam, P. Dollár, and J.H. Han
%   "Local Decorrelation For Improved Pedestrian Detection," NIPS 2014.
