### ISSUE TITLE
Error using feval: Undefined function 'rnlfilt_max' for input arguments of type 'double'.

### ISSUE THREAD

**Issue by CathleenYu** [pdollar/toolbox#20]
I'm using your Computer Vision Matlab Toolbox v1.03 for 'Cuboids code'. In the line 60 of the file '\toolbox\images\nonmaxsupr.m' ,  you use a function 'rnlfilt_max'. But I can not fine the definition in your toolbox. I wonder if is there anything wrong?

**Comment by pdollar** [comment]
You probably didn't compile the toolbox. I'm not supporting that version anymore but good luck.

**Comment by CathleenYu** [comment]
yes, it is because I didn't compile the toolbox. Thank you so much.

**Comment by OmFiras** [comment]
I found the same problem. Please, how to compile the toolbox. I tried
  >> toolboxCompile; 
but it does not work.
