### ISSUE TITLE
Undefined function or variable 'int2str2'

### ISSUE THREAD

**Issue by Yuzz1020** [pdollar/toolbox#54]
Thank you for sharing this great toolbox. There is something wrong when I try to use the tool box in my end. 

I'm running the code on my Mac system. However, when I try to run seqIo.m with command 
`out = seqIo('/MY/PATH/TO/SEQ/FILENAME.seq','reader')`
It ends up with error

> Undefined function or variable 'int2str2'.
> 
> Error in seqReaderPlugin>readHeader (line 219)
> fps = fread(fid,1,'float64'); codec=['imageFormat' int2str2(tmp(6),3)];
> 
> Error in seqReaderPlugin>open (line 96)
> if(isempty(info)), info=readHeader(fid); else
> 
> Error in seqReaderPlugin (line 47)
>   [infos{h},fids(h),tNms{h}]=open(fName,info); return;
> 
> Error in seqIo>reader (line 113)
> r=@seqReaderPlugin; s=r('open',int32(-1),fName);
> 
> Error in seqIo (line 64)
>   case {'reader','r'}, out = reader( fName, varargin{:} );
> 
> Error in untitled (line 1)
> out = seqIo('/MY/PATH/TO/SEQ/FILENAME.seq','reader')

Is this a bug or I didn't correctly installed the code? 

Any help would be appreciated.

**Comment by lhs21** [comment]
hello，I have met the similiar problem，have you solved it yet？

Undefined function or variable 'int2str2'

Error in dbExtract (line 37)
    fs=cell(1,n); for i=1:n, fs{i}=[f 'I' int2str2(i-1,5)]; end

It'll be great if you can reply me!!

**Comment by jquan7** [comment]
NOTE here:
Simply unzip, then add all directories to the Matlab path:
  >> addpath(genpath('**path/to/toolbox/**')); savepath;

If needed, run the compile script for the mex files:
  >> toolboxCompile;
Note: **64 bit Windows/Linux/Mac binaries are already included.**

when I type :  addpath(genpath('**path/to/toolbox/videos**')); savepath;  
problem arise.
